name: Build
on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd frontend && npm install
      - name: Build
        run: cd frontend && npm run build
      - name: Test
        run: cd frontend && npm run test
      - name: debug
        run: ls -la && ls -la frontend
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: frontend/build
